/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package in.raster.mayam.process;

import com.pixelmed.dicom.Attribute;
import com.pixelmed.dicom.AttributeList;
import com.pixelmed.dicom.AttributeTag;
import com.pixelmed.dicom.DecimalStringAttribute;
import com.pixelmed.dicom.DicomException;
import com.pixelmed.dicom.LongStringAttribute;
import ij.IJ;
import ij.ImagePlus;
import in.raster.mayam.context.ApplicationContext;
import in.raster.mayam.models.ResultModel;
import in.raster.mayam.process.rgrowing.MultiRegionManagerModel;
import in.raster.mayam.process.rgrowing.MultiRegionManagerView;
import in.raster.mayam.process.rgrowing.RegionGrowingModel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseWheelEvent;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;


/**
 *
 * @author mariano
 */
public class ImageProcessing extends JFrame {

    private BufferedImage originalImage = null;
    private BufferedImage isolatedImage = null;
    private BufferedImage outlinedImage = null;
    private BufferedImage binaryImage = null;
    private ImagePanel imgPane = null;
    private static int SEG_OPT_NONE = 0;
    private static int SEG_OPT_OTSU = 1;
    private static int SEG_OPT_RGROWING = 2;
    
    /**
     * Creates new form ImageProcessing
     */
    public ImageProcessing(BufferedImage img) {
//        setModal(true);
        originalImage = img;
        imgPane = new ImagePanel();
        initComponents();
        imgPane.setImage(img);
        patienNameLabel.setText(ApplicationContext.imgView.getPatientInfo()[0]+
                " - " + ApplicationContext.imgView.getPatientInfo()[1]);
        studyDateLabel.setText(ApplicationContext.imgView.getPatientInfo()[3]);
        studyDescLabel.setText(ApplicationContext.imgView.getPatientInfo()[2]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        areaField = new javax.swing.JTextField();
        perimeterField = new javax.swing.JTextField();
        diamField = new javax.swing.JTextField();
        symField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        circField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        rectField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        imgIcon = new javax.swing.JLabel();
        patienNameLabel = new javax.swing.JLabel();
        studyDateLabel = new javax.swing.JLabel();
        studyDescLabel = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        grayFromButton = new javax.swing.JButton();
        grayToButton = new javax.swing.JButton();
        redFromButton = new javax.swing.JButton();
        redToButton = new javax.swing.JButton();
        brownFromButton = new javax.swing.JButton();
        javax.swing.JButton brownToButton = new javax.swing.JButton();
        grayFromIcon = new javax.swing.JPanel();
        redFromIcon = new javax.swing.JPanel();
        brownFromIcon = new javax.swing.JPanel();
        grayToIcon = new javax.swing.JPanel();
        redToIcon = new javax.swing.JPanel();
        brownToIcon = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        imgScrollPane = new JScrollPane(imgPane);
        algoCombo = new javax.swing.JComboBox();
        analyzeButton = new javax.swing.JButton();
        undoButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        saveInDicom = new javax.swing.JCheckBox();
        showCombo = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(ApplicationContext.currentBundle.getString("ImageProcessing.window.title")); // NOI18N
        setAlwaysOnTop(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dimensiones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("DejaVu Sans", 0, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        jLabel1.setText("Area");

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        jLabel2.setText("Perimetro");

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        jLabel3.setText("Simetria");

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        jLabel4.setText("Diametro");

        areaField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        areaField.setEnabled(false);

        perimeterField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        perimeterField.setEnabled(false);

        diamField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        diamField.setEnabled(false);

        symField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        symField.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        jLabel11.setText("Circularidad");

        circField.setEditable(false);
        circField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        circField.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        jLabel16.setText("Rectangularidad");

        rectField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        rectField.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(areaField, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(perimeterField)
                    .addComponent(diamField)
                    .addComponent(symField)
                    .addComponent(circField)
                    .addComponent(rectField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(areaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(perimeterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(symField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(diamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(circField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rectField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Scores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("DejaVu Sans", 0, 12))); // NOI18N

        jLabel6.setText("A:");

        jLabel7.setText("B:");

        jLabel8.setText("C:");

        jLabel9.setText("D:");

        jLabel10.setText("TDS");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(54, 54, 54))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        patienNameLabel.setText("pname");

        studyDateLabel.setText("sdate");

        studyDescLabel.setText("sdesc");

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTabbedPane1.setName("Colores"); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setPreferredSize(new java.awt.Dimension(371, 107));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Colores", jPanel4);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setText("Tonos Marron:");

        jLabel13.setText("Tonos gris:");

        jLabel14.setText("Tonos Rojos:");

        grayFromButton.setText("...");
        grayFromButton.setMaximumSize(new java.awt.Dimension(40, 25));
        grayFromButton.setMinimumSize(new java.awt.Dimension(40, 25));
        grayFromButton.setPreferredSize(new java.awt.Dimension(40, 25));
        grayFromButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grayFromButtonActionPerformed(evt);
            }
        });

        grayToButton.setText("...");
        grayToButton.setMaximumSize(new java.awt.Dimension(25, 25));
        grayToButton.setMinimumSize(new java.awt.Dimension(25, 25));
        grayToButton.setPreferredSize(new java.awt.Dimension(25, 25));
        grayToButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grayToButtonActionPerformed(evt);
            }
        });

        redFromButton.setText("...");
        redFromButton.setMaximumSize(new java.awt.Dimension(25, 25));
        redFromButton.setMinimumSize(new java.awt.Dimension(25, 25));
        redFromButton.setPreferredSize(new java.awt.Dimension(25, 25));
        redFromButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redFromButtonActionPerformed(evt);
            }
        });

        redToButton.setText("...");
        redToButton.setMaximumSize(new java.awt.Dimension(25, 25));
        redToButton.setMinimumSize(new java.awt.Dimension(25, 25));
        redToButton.setPreferredSize(new java.awt.Dimension(25, 25));
        redToButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redToButtonActionPerformed(evt);
            }
        });

        brownFromButton.setText("...");
        brownFromButton.setMaximumSize(new java.awt.Dimension(25, 25));
        brownFromButton.setMinimumSize(new java.awt.Dimension(25, 25));
        brownFromButton.setPreferredSize(new java.awt.Dimension(25, 25));
        brownFromButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brownFromButtonActionPerformed(evt);
            }
        });

        brownToButton.setText("...");
        brownToButton.setMaximumSize(new java.awt.Dimension(25, 25));
        brownToButton.setMinimumSize(new java.awt.Dimension(25, 25));
        brownToButton.setPreferredSize(new java.awt.Dimension(25, 25));
        brownToButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brownToButtonActionPerformed(evt);
            }
        });

        grayFromIcon.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        grayFromIcon.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout grayFromIconLayout = new javax.swing.GroupLayout(grayFromIcon);
        grayFromIcon.setLayout(grayFromIconLayout);
        grayFromIconLayout.setHorizontalGroup(
            grayFromIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        grayFromIconLayout.setVerticalGroup(
            grayFromIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        redFromIcon.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        redFromIcon.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout redFromIconLayout = new javax.swing.GroupLayout(redFromIcon);
        redFromIcon.setLayout(redFromIconLayout);
        redFromIconLayout.setHorizontalGroup(
            redFromIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        redFromIconLayout.setVerticalGroup(
            redFromIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        brownFromIcon.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        brownFromIcon.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout brownFromIconLayout = new javax.swing.GroupLayout(brownFromIcon);
        brownFromIcon.setLayout(brownFromIconLayout);
        brownFromIconLayout.setHorizontalGroup(
            brownFromIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        brownFromIconLayout.setVerticalGroup(
            brownFromIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        grayToIcon.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        grayToIcon.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout grayToIconLayout = new javax.swing.GroupLayout(grayToIcon);
        grayToIcon.setLayout(grayToIconLayout);
        grayToIconLayout.setHorizontalGroup(
            grayToIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        grayToIconLayout.setVerticalGroup(
            grayToIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        redToIcon.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        redToIcon.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout redToIconLayout = new javax.swing.GroupLayout(redToIcon);
        redToIcon.setLayout(redToIconLayout);
        redToIconLayout.setHorizontalGroup(
            redToIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        redToIconLayout.setVerticalGroup(
            redToIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        brownToIcon.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        brownToIcon.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout brownToIconLayout = new javax.swing.GroupLayout(brownToIcon);
        brownToIcon.setLayout(brownToIconLayout);
        brownToIconLayout.setHorizontalGroup(
            brownToIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        brownToIconLayout.setVerticalGroup(
            brownToIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(brownFromButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(redFromButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grayFromButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(redFromIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(redToButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(grayFromIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(grayToButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(brownFromIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(brownToButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(grayToIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(redToIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brownToIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(7, 7, 7))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(grayToIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(grayFromButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(grayToButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(grayFromIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(redFromButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(redToButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(redToIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(redFromIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(brownToIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(brownFromButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brownToButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(brownFromIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(8, 8, 8))
        );

        jTabbedPane1.addTab("Config", jPanel6);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Borde", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("DejaVu Sans", 0, 12))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(371, 107));

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        jLabel5.setText("Irregularidad");

        jTextField1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField1.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel5))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(studyDescLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(patienNameLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(studyDateLabel)))
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(studyDateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(patienNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(studyDescLabel)
                .addContainerGap())
        );

        imgScrollPane.setAutoscrolls(true);
        imgScrollPane.setPreferredSize(new java.awt.Dimension(665, 937));

        algoCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Método segmentación...", "Otsu", "Region Growing" }));

        analyzeButton.setText("Calcular");
        analyzeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyzeButtonActionPerformed(evt);
            }
        });

        undoButton.setText("Deshacer");
        undoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Guardar");
        saveButton.setMaximumSize(new java.awt.Dimension(78, 27));
        saveButton.setMinimumSize(new java.awt.Dimension(78, 27));
        saveButton.setPreferredSize(new java.awt.Dimension(78, 27));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        saveInDicom.setText(ApplicationContext.currentBundle.getString("ImageProcessing.saveInDicom")); // NOI18N
        saveInDicom.setToolTipText(ApplicationContext.currentBundle.getString("ImageProcessing.saveInDicom.tooltip")); // NOI18N

        showCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bordes", "Aislado", "Binario" }));
        showCombo.setEnabled(false);
        showCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showComboActionPerformed(evt);
            }
        });

        jLabel15.setText("Ver:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imgScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(analyzeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(undoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(algoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showCombo, 0, 122, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveInDicom))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(undoButton)
                            .addComponent(algoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(analyzeButton)
                            .addComponent(showCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveInDicom)
                            .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imgScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void analyzeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyzeButtonActionPerformed

        if (algoCombo.getSelectedIndex()== SEG_OPT_NONE) {
            JOptionPane.showMessageDialog(this, "mensaje", "title", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (this.algoCombo.getSelectedIndex() == SEG_OPT_OTSU) {
            ImagePlus imp = new ImagePlus("", originalImage);
            IJ.run(imp, "8-bit", "");
            OtsuThresholding_ otsu = (OtsuThresholding_) IJ.runPlugIn(imp, "in.raster.mayam.process.OtsuThresholding_", "");
            ImagePlus tempImp = otsu.getImp();
            IJ.run(tempImp, "Fill Holes", "");
            ParticleRemover pr = (ParticleRemover) IJ.runPlugIn(tempImp, "in.raster.mayam.process.ParticleRemover", "");
        
            ImagePlus prImp = pr.getImp();
            binaryImage = prImp.getBufferedImage();
            
            CustomParticleAnalyzerPlugin cpa = (CustomParticleAnalyzerPlugin) IJ.runPlugIn(prImp, "in.raster.mayam.process.CustomParticleAnalyzerPlugin","");
            this.areaField.setText(String.valueOf(cpa.getArea()));
            this.perimeterField.setText(String.valueOf(cpa.getPerimeter()));
            this.diamField.setText(String.valueOf(cpa.getFeretDiam()));
            this.circField.setText(String.valueOf(cpa.getCircularity()));
            this.rectField.setText(String.valueOf(cpa.getRectangularity()));
            
            RegionExtraction re = new RegionExtraction(originalImage, prImp.getBufferedImage());
            re.execute();
            
            isolatedImage = re.getIsolatedImage().getBufferedImage();
            
            //IJ.runPlugIn(imp,"in.raster.mayam.process.ColorCounter", "");
        
            //parametros para dibujo de EJE Mayor y EJE Menor:
            String X = String.valueOf(cpa.getCentroid().x);
            String Y = String.valueOf(cpa.getCentroid().y);
            String MAJOR = String.valueOf(cpa.getMajor());
            String MINOR = String.valueOf(cpa.getMinor());
            String ANGLE = String.valueOf(cpa.getAngle());
            AxesPlugin ap = (AxesPlugin) IJ.runPlugIn(re.getOutlinedImage(),"in.raster.mayam.process.AxesPlugin",
                X+","+Y+","+MAJOR+","+MINOR+","+ANGLE);
        
            outlinedImage = ap.getBufferedImage();
            
            imgPane.setImage(outlinedImage);
            
            if (showCombo.getItemCount() == 2) {
                showCombo.addItem("Binary");
            }
            showCombo.setEnabled(true);
            showCombo.setSelectedIndex(0);
        }
        
        if (this.algoCombo.getSelectedIndex() == SEG_OPT_RGROWING) {
            ImagePlus imp = new ImagePlus("", originalImage);
            MultiRegionManagerView rgView = new MultiRegionManagerView(imp);
            rgView.setLocationRelativeTo(this);
            rgView.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            rgView.setModal(true);
            rgView.setVisible(true);
            if (rgView.isAccepted()) {
            
                MultiRegionManagerModel mRgModel = rgView.getModel();
                RegionGrowingModel rgModel = new RegionGrowingModel(mRgModel);
                rgModel.actionRun();
                ImagePlus rgImp = rgModel.getImpResult();

                IJ.run(rgImp, "8-bit", "");           
                CustomParticleAnalyzerPlugin cpa = (CustomParticleAnalyzerPlugin) IJ.runPlugIn(rgImp, "in.raster.mayam.process.CustomParticleAnalyzerPlugin","");
                this.areaField.setText(String.valueOf(cpa.getArea()));
                this.perimeterField.setText(String.valueOf(cpa.getPerimeter()));
                this.diamField.setText(String.valueOf(cpa.getFeretDiam()));
                this.circField.setText(String.valueOf(cpa.getCircularity()));
                this.rectField.setText(String.valueOf(cpa.getRectangularity()));
                
                RegionExtraction re = new RegionExtraction(originalImage, rgImp.getBufferedImage());
                re.execute();

                isolatedImage = re.getIsolatedImage().getBufferedImage();

                //parametros para dibujo de EJE Mayor y EJE Menor:
                String X = String.valueOf(cpa.getCentroid().x);
                String Y = String.valueOf(cpa.getCentroid().y);
                String MAJOR = String.valueOf(cpa.getMajor());
                String MINOR = String.valueOf(cpa.getMinor());
                String ANGLE = String.valueOf(cpa.getAngle());
                AxesPlugin ap = (AxesPlugin) IJ.runPlugIn(re.getOutlinedImage(),"in.raster.mayam.process.AxesPlugin",
                    X+","+Y+","+MAJOR+","+MINOR+","+ANGLE);

                outlinedImage = ap.getBufferedImage();

                imgPane.setImage(outlinedImage);

                showCombo.setEnabled(true);
                if (showCombo.getItemCount()==3) {
                    showCombo.removeItemAt(2);
                }
                showCombo.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_analyzeButtonActionPerformed

    private void undoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoButtonActionPerformed
        imgPane.setImage(originalImage);
    }//GEN-LAST:event_undoButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        //System.out.println(ApplicationContext.imgView.getPatientInfo()[1]);
        //System.out.println(ApplicationContext.imgView.getPatientInfo()[5]);
        ResultModel result = new ResultModel();
        result.setPatientId(ApplicationContext.imgView.getPatientInfo()[1]);
        result.setStudyIUID(ApplicationContext.imgView.getPatientInfo()[5]);
        result.setValueA("1.0");
        result.setValueB("1.5");
        result.setValueC("0.5");
        result.setValueD("0.1");
        result.setTDS("2.5");
        if (ApplicationContext.databaseRef.checkResultExists(result)) {
            int r = JOptionPane.showConfirmDialog(this, ApplicationContext.currentBundle.getString("ImageProcessing.result.overwrite"),
                    ApplicationContext.currentBundle.getString("ImageProcessing.result.warning"), JOptionPane.OK_CANCEL_OPTION);
            if (JOptionPane.CANCEL_OPTION == r) {
                return;
            }
            ApplicationContext.databaseRef.updateResult(result);
        } else {
            ApplicationContext.databaseRef.insertResult(result);
        }
        if (saveInDicom.isSelected()) {
            saveInDicom(result);
        }
        JOptionPane.showMessageDialog(this, ApplicationContext.currentBundle.getString("ImageProcessing.result.saved"));
    }//GEN-LAST:event_saveButtonActionPerformed

    private void grayFromButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grayFromButtonActionPerformed
        Color newColor = JColorChooser.showDialog(
                     this,
                     "Choose Background Color",
                     Color.WHITE);
        this.grayFromIcon.setBackground(newColor);
    }//GEN-LAST:event_grayFromButtonActionPerformed

    private void redFromButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redFromButtonActionPerformed
        Color newColor = JColorChooser.showDialog(
                     this,
                     "Choose Background Color",
                     Color.WHITE);
        this.redFromIcon.setBackground(newColor);
    }//GEN-LAST:event_redFromButtonActionPerformed

    private void brownFromButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brownFromButtonActionPerformed
        Color newColor = JColorChooser.showDialog(
                     this,
                     "Choose Background Color",
                     Color.WHITE);
       this.brownFromIcon.setBackground(newColor);
    }//GEN-LAST:event_brownFromButtonActionPerformed

    private void grayToButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grayToButtonActionPerformed
        Color newColor = JColorChooser.showDialog(
                     this,
                     "Choose Background Color",
                     Color.WHITE);
        this.grayToIcon.setBackground(newColor);
    }//GEN-LAST:event_grayToButtonActionPerformed

    private void redToButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redToButtonActionPerformed
        Color newColor = JColorChooser.showDialog(
                     this,
                     "Choose Background Color",
                     Color.WHITE);
        this.redToIcon.setBackground(newColor);
    }//GEN-LAST:event_redToButtonActionPerformed

    private void brownToButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brownToButtonActionPerformed
        Color newColor = JColorChooser.showDialog(
                     this,
                     "Choose Background Color",
                     Color.WHITE);
        this.brownToIcon.setBackground(newColor);
    }//GEN-LAST:event_brownToButtonActionPerformed

    private void showComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showComboActionPerformed
        switch (showCombo.getSelectedIndex()) {
            case 0: imgPane.setImage(outlinedImage);
                break;
            case 1: imgPane.setImage(isolatedImage);
                break;
            case 2: imgPane.setImage(binaryImage);
                break;
            default: break;    
        }
    }//GEN-LAST:event_showComboActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox algoCombo;
    private javax.swing.JButton analyzeButton;
    private javax.swing.JTextField areaField;
    private javax.swing.JButton brownFromButton;
    private javax.swing.JPanel brownFromIcon;
    private javax.swing.JPanel brownToIcon;
    private javax.swing.JTextField circField;
    private javax.swing.JTextField diamField;
    private javax.swing.JButton grayFromButton;
    private javax.swing.JPanel grayFromIcon;
    private javax.swing.JButton grayToButton;
    private javax.swing.JPanel grayToIcon;
    private javax.swing.JLabel imgIcon;
    private javax.swing.JScrollPane imgScrollPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel patienNameLabel;
    private javax.swing.JTextField perimeterField;
    private javax.swing.JTextField rectField;
    private javax.swing.JButton redFromButton;
    private javax.swing.JPanel redFromIcon;
    private javax.swing.JButton redToButton;
    private javax.swing.JPanel redToIcon;
    private javax.swing.JButton saveButton;
    private javax.swing.JCheckBox saveInDicom;
    private javax.swing.JComboBox showCombo;
    private javax.swing.JLabel studyDateLabel;
    private javax.swing.JLabel studyDescLabel;
    private javax.swing.JTextField symField;
    private javax.swing.JButton undoButton;
    // End of variables declaration//GEN-END:variables

    /**
     * Guarda resultados de ABCD en el archivo DICOM
     * @param result 
     */
    private void saveInDicom(ResultModel result) {
        String srcFilePath = ApplicationContext.layeredCanvas.imgpanel.getDicomFileUrl();
        try {
            AttributeList list = new AttributeList();
            list.read(srcFilePath);
            
            AttributeTag abcdTag = new AttributeTag(0x0019,0x0010);
            Attribute abcdAttr = new LongStringAttribute(abcdTag);
            abcdAttr.addValue("ABCD Result values");
            list.put(abcdAttr);
            
            AttributeTag aTag = new AttributeTag(0x0019,0x1010);
            Attribute aAttr = new DecimalStringAttribute(aTag);
            aAttr.addValue(result.getValueA());
            list.put(aAttr);
            
            AttributeTag bTag = new AttributeTag(0x0019,0x1020);
            Attribute bAttr = new DecimalStringAttribute(bTag);
            bAttr.addValue(result.getValueB());
            list.put(bAttr);
            
            AttributeTag cTag = new AttributeTag(0x0019,0x1030);
            Attribute cAttr = new DecimalStringAttribute(cTag);
            cAttr.addValue(result.getValueC());
            list.put(cAttr);
            
            AttributeTag dTag = new AttributeTag(0x0019,0x1040);
            Attribute dAttr = new DecimalStringAttribute(dTag);
            dAttr.addValue(result.getValueD());
            list.put(dAttr);
            
            AttributeTag rTag = new AttributeTag(0x0019,0x1050);
            Attribute rAttr = new DecimalStringAttribute(rTag);
            rAttr.addValue(result.getTDS());
            list.put(rAttr);
//          System.out.println(ClinicalTrialsAttributes.isSafePrivateAttribute(e.getTag().),list));
//            for (AttributeTag tag : list.keySet()) {
//                System.out.println(tag.toString()+":"+list.get(tag).getVRAsString()+list.get(tag).getVM());
//            }
            list.write(srcFilePath);
        } catch (IOException ex) {
            Logger.getLogger(ImageProcessing.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DicomException ex) {
            Logger.getLogger(ImageProcessing.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private class ImagePanel extends JPanel {

        BufferedImage image;
        float scale;
        
        public ImagePanel() {
            scale = 1;
            addMouseWheelListener(new MouseAdapter() {
                @Override
                public void mouseWheelMoved(MouseWheelEvent e) {
                    double delta = 0.01f * e.getPreciseWheelRotation();
                    scale += delta;
                    revalidate();
                    repaint();
                }
            });
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            if (image != null) {
                Graphics2D g2d = (Graphics2D) g.create();
//                g2d.setRenderingHint(RenderingHints.KEY_INTERPOLATION,
//                        RenderingHints.VALUE_INTERPOLATION_BICUBIC);
                double x = (getWidth() - scale * image.getWidth()) / 2;
                double y = (getHeight() - scale * image.getHeight()) / 2;
                AffineTransform at = AffineTransform.getTranslateInstance(x, y);
                at.scale(scale, scale);
//                g2d.drawRenderedImage(image, atg2d.drawImage(image, at, this););
                g2d.drawImage(image, at, this);
                g2d.dispose();
            }
        }

        @Override
        public Dimension getPreferredSize() {
            Dimension size = new Dimension();
            if (image!=null){
                size.width =  Math.round(scale * image.getWidth());
                size.height =  Math.round(scale * image.getHeight());
            }
            return size;
        }
           
        public void setImage(BufferedImage image) {
            this.image = image;
            revalidate();
            repaint();
        }
        
    }
}
